# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.19.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: "Run unit tests"
  inputs:
    script: |
      cd angular-app/
      ng test --browsers=chromeHeadless --code-coverage --watch=false

      - task: ArchieveFiles@2
        displayName:  'Archieve files'
        inputs:
          rootFolderOrFile: '$ (System.DefaultWorkingDirectory)/dist/angular-app/'
          includeRootFolder: false
          archieveType: zip
          archieveFile: $ (Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchieve: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$ (Build.ArtifactStagingDirectory)/$ (Build.BuildId).zip'
              ArtifactName: 'drop'
              publishLocation: 'container'